# step 1: from a dev branch, git push
# step 2: pull request to main branch
# another file cd.yml will execute step 3 (after merging to main branch)
name: CI
on: [pull_request]
jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Spin up containers
        run: make up
      - name: Run CI test
        run: make ci
